### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by gtnl** [sgsoft-studio/webed#59] opened 2018-03-11 10:02 UTC
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'WebEd\Base\CustomFields\Facades\CustomFieldSupportFacade' not found

**Comment by rafayhingoro** [comment] 2018-03-22 11:28
duplicate of and answered [here](https://github.com/sgsoft-studio/webed/issues/57#issuecomment-370630884)

**Comment by duysolo** [comment] 2018-03-22 12:12
I fixed this issues.

**Closed as completed by duysolo** 2018-03-22 12:12 UTC
